name: doan_hk2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/nen.jpg
    - assets/0106_hinh-nen-4k-may-tinh33.jpg
    - assets/anime-girl-windows-11-4k-wallpaper-uhdpaper.com-320@2@b.jpg
    - assets/anime-one-piece-monkey-d-luffy-wallpaper-preview.jpg
