name: doan_hk2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  carousel_slider: ^4.2.0 
  shared_preferences: ^2.3.5
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:

   
    - assets/Cam.jpg
    - assets/XoaiXanh.jpg
    - assets/Tao.jpg
    - assets/Nho.jpg
    - assets/SauRieng.jpg
    - assets/TaoDo.jpg
    - assets/OiHong.jpg
    - assets/anh.gif
    - assets/banane.jpg
    - assets/thanhtoan.jpg

